name: easebuzz_flutter_sdk
description: "The Easebuzz Flutter SDK streamlines secure payment integration across Android, iOS, and web platforms."
version: 1.0.0
homepage: https://www.techienutzitservices.com/
repository: https://github.com/techienutz/easebuzz_flutter_sdk
issue_tracker: https://github.com/techienutz/easebuzz_flutter_sdk/issues

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

topics:
  - payment
  - sdk
  - cross-platform

dependencies:
  crypto: ^3.0.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  web: ^0.5.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.easebuzzFlutterSdk
        pluginClass: EasebuzzFlutterSdkPlugin
      ios:
        pluginClass: EasebuzzFlutterSdkPlugin
      web:
        pluginClass: EasebuzzFlutterSdkWeb
        fileName: easebuzz_flutter_sdk_web.dart