class EasebuzzPaymentModel {
  /// Unique Merchant Key provided by Easebuzz for identifying the merchant account.
  final String key;

  /// Transaction ID (Order ID) generated by the merchant to track the order. Must be unique for each transaction.
  final String txnid;

  /// Payment amount for the transaction. Should be a float type.
  final double amount;

  /// This parameter should contain a brief product description. It should be a string describing the product (The description type is entirely your choice).Allowed characters : Letters, numbers,hyphen,space
  /// Match pattern:^[a-zA-Z0-9-\s\|\-]*$
  final String productinfo;

  /// First name of the customer making the payment.
  final String firstname;

  /// Phone number of the customer.
  final String phone;

  /// Email ID of the customer for communication and receipts.
  final String email;

  /// Success URL where the user will be redirected after a successful transaction.
  final String surl;

  /// Failure URL where the user will be redirected if the transaction fails.
  final String furl;

  /// SHA512 encrypted hash for transaction security to prevent tampering.
  String? hash;

  // Optional parameters for additional information
  /// User defined field 1 for any additional information related to the transaction.
  final String? udf1;

  /// User defined field 2 for additional information.
  final String? udf2;

  /// User defined field 3 for additional information.
  final String? udf3;

  /// User defined field 4 for additional information.
  final String? udf4;

  /// User defined field 5 for additional information.
  final String? udf5;

  /// User defined field 6 for additional information.
  final String? udf6;

  /// User defined field 7 for additional information.
  final String? udf7;

  /// Optional address field 1 for the customer's address.
  final String? address1;

  /// Optional address field 2 for the customer's address.
  final String? address2;

  /// Customer's city for billing or shipping purposes.
  final String? city;

  /// Customer's state for billing or shipping purposes.
  final String? state;

  /// Customer's country for billing or shipping purposes.
  final String? country;

  /// Customer's zipcode for billing or shipping purposes.
  final String? zipcode;

  /// Details for displaying the payment mode to the user.
  final String? showPaymentMode;

  /// Details for splitting the transaction amount across multiple accounts if enabled.
  /// { "Easebuzztest 1": 11.0, "Easebuzztest 2": 1.0 }
  final String? splitPayments;

  /// For Seamless Payment, pass "SEAMLESS" to indicate the payment flow.
  final String? requestFlow;

  /// Submerchant ID for aggregator setup, mandatory if using an aggregator.
  final String? subMerchantId;

  /// For Third Party Validation (TPV) payments, specify the payment category.
  final String? paymentCategory;

  /// Customer's account number for TPV validation.
  final String? accountNo;

  /// Customer's IFSC code for TPV validation.
  final String? ifsc;

  EasebuzzPaymentModel({
    required this.key,
    required this.txnid,
    required this.amount,
    required this.productinfo,
    required this.firstname,
    required this.phone,
    required this.email,
    required this.surl,
    required this.furl,
    this.hash,
    this.udf1,
    this.udf2,
    this.udf3,
    this.udf4,
    this.udf5,
    this.udf6,
    this.udf7,
    this.address1,
    this.address2,
    this.city,
    this.state,
    this.country,
    this.zipcode,
    this.showPaymentMode,
    this.splitPayments,
    this.requestFlow,
    this.subMerchantId,
    this.paymentCategory,
    this.accountNo,
    this.ifsc,
  });

  // Convert model to JSON
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{
      'key': key,
      'txnid': txnid,
      'amount': amount,
      'productinfo': productinfo,
      'firstname': firstname,
      'phone': phone,
      'email': email,
      'surl': surl,
      'furl': furl,
      'hash': hash,
    };

    // Add optional parameters only if they are not null
    if (udf1 != null) data['udf1'] = udf1;
    if (udf2 != null) data['udf2'] = udf2;
    if (udf3 != null) data['udf3'] = udf3;
    if (udf4 != null) data['udf4'] = udf4;
    if (udf5 != null) data['udf5'] = udf5;
    if (udf6 != null) data['udf6'] = udf6;
    if (udf7 != null) data['udf7'] = udf7;
    if (address1 != null) data['address1'] = address1;
    if (address2 != null) data['address2'] = address2;
    if (city != null) data['city'] = city;
    if (state != null) data['state'] = state;
    if (country != null) data['country'] = country;
    if (zipcode != null) data['zipcode'] = zipcode;
    if (showPaymentMode != null) data['show_payment_mode'] = showPaymentMode;
    if (splitPayments != null) data['split_payments'] = splitPayments;
    if (requestFlow != null) data['request_flow'] = requestFlow;
    if (subMerchantId != null) data['sub_merchant_id'] = subMerchantId;
    if (paymentCategory != null) data['payment_category'] = paymentCategory;
    if (accountNo != null) data['account_no'] = accountNo;
    if (ifsc != null) data['ifsc'] = ifsc;

    return data;
  }

  // Create model from JSON
  factory EasebuzzPaymentModel.fromJson(Map<String, dynamic> json) {
    return EasebuzzPaymentModel(
      key: json['key'],
      txnid: json['txnid'],
      amount: double.parse(json['amount'].toString()),
      productinfo: json['productinfo'],
      firstname: json['firstname'],
      phone: json['phone'],
      email: json['email'],
      surl: json['surl'],
      furl: json['furl'],
      hash: json['hash'],
      udf1: json['udf1'],
      udf2: json['udf2'],
      udf3: json['udf3'],
      udf4: json['udf4'],
      udf5: json['udf5'],
      udf6: json['udf6'],
      udf7: json['udf7'],
      address1: json['address1'],
      address2: json['address2'],
      city: json['city'],
      state: json['state'],
      country: json['country'],
      zipcode: json['zipcode'],
      showPaymentMode: json['show_payment_mode'],
      splitPayments: json['split_payments'],
      requestFlow: json['request_flow'],
      subMerchantId: json['sub_merchant_id'],
      paymentCategory: json['payment_category'],
      accountNo: json['account_no'],
      ifsc: json['ifsc'],
    );
  }
}
